# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/basys3.xdc

# IP: ip/explosions_br/explosions_br.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==explosions_br || ORIG_REF_NAME==explosions_br} -quiet] -quiet

# IP: ip/bomb_dm_1/bomb_dm.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bomb_dm || ORIG_REF_NAME==bomb_dm} -quiet] -quiet
