# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.runs/synth_1/top_module.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.cache/wt [current_project]
set_property parent.project_path /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/graphics/pillar.coe
add_files /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/graphics/player.coe
add_files /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/graphics/player_death.coe
add_files /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/graphics/bomb.coe
add_files /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/graphics/explosions.coe
add_files /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/graphics/enemy.coe
add_files /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/graphics/block.coe
add_files /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/graphics/block_map.coe
read_verilog -library xil_defaultlib -sv {
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/LFSR_16.sv
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/bomberman_module.sv
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/clk_divider.sv
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/vga_sync.sv
}
read_verilog -library xil_defaultlib {
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/block_module.v
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/bomb_module.v
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/debounce_button.v
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/enemy_module.v
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/game_lives.v
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/numbers_rom.v
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/pillar_display.v
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/score_display.v
  /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/top_module.v
}
read_ip -quiet /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/explosions_br/explosions_br.xci
set_property used_in_implementation false [get_files -all /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/explosions_br/explosions_br_ooc.xdc]

read_ip -quiet /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/bomb_dm_1/bomb_dm.xci
set_property used_in_implementation false [get_files -all /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/bomb_dm_1/bomb_dm_ooc.xdc]

read_ip -quiet /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/bm_sprite_br/bm_sprite_br.xci
set_property used_in_implementation false [get_files -all /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/bm_sprite_br/bm_sprite_br_ooc.xdc]

read_ip -quiet /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/player_death_br/player_death_br.xci
set_property used_in_implementation false [get_files -all /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/player_death_br/player_death_br_ooc.xdc]

read_ip -quiet /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/pillar_dm/pillar_dm.xci
set_property used_in_implementation false [get_files -all /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/pillar_dm/pillar_dm_ooc.xdc]

read_ip -quiet /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/block_dm/block_dm.xci
set_property used_in_implementation false [get_files -all /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/block_dm/block_dm_ooc.xdc]

read_ip -quiet /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/block_map_1/block_map.xci
set_property used_in_implementation false [get_files -all /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/block_map_1/block_map_ooc.xdc]

read_ip -quiet /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/enemy_sprite_br/enemy_sprite_br.xci
set_property used_in_implementation false [get_files -all /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/enemy_sprite_br/enemy_sprite_br_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/basys3.xdc
set_property used_in_implementation false [get_files /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/HDL_Incomplete/basys3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.srcs/utils_1/imports/synth_1/top_module.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_module -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
