# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/block_dm/block_dm.xci
# IP: The module: 'block_dm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/block_dm/block_dm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_dm'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.srcs/sources_1/ip/block_dm/block_dm.xci
# IP: The module: 'block_dm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/alex/secondaryLinux/FPGALAB/fpga-final-project/bomberman_student_2024/bomberman_basys3/bomberman_basys3.gen/sources_1/ip/block_dm/block_dm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_dm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
